import { TagName, RowPosition, ColumPosition } from '@biz-components/Tag/schema';

export const config = {
  tag_name: TagName.FONT1,
  tag_props: {
    height: 40,
    width: 100,
  },
  tag_children: [{
    tag_name: TagName.TEXT1,
    tag_props: {
      height: 20,
      width: 33.33,
      row_position: RowPosition.CENTER,
      column_position: ColumPosition.CENTER,
      font_size: 7,
      left: 33.33,
      top: 0,
      content: '文字段落',
      color: '#666',
      font_weight: 500,
    },
  }, {
    tag_name: TagName.TEXT1,
    tag_props: {
      height: 20,
      width: 33.33,
      row_position: RowPosition.CENTER,
      column_position: ColumPosition.CENTER,
      font_size: 7,
      left: 66.66,
      top: 0,
      content: '文字段落',
      color: '#666',
      font_weight: 500,
    },
  }, {
    tag_name: TagName.TEXT1,
    tag_props: {
      height: 20,
      width: 33.33,
      row_position: RowPosition.CENTER,
      column_position: ColumPosition.CENTER,
      font_size: 7,
      left: 0,
      top: 0,
      content: '文字段落',
      color: '#666',
      font_weight: 500,
    },
  }, {
    tag_name: TagName.TEXT1,
    tag_props: {
      height: 20,
      width: 33.33,
      row_position: RowPosition.CENTER,
      column_position: ColumPosition.CENTER,
      font_size: 7,
      left: 33.33,
      top: 20,
      content: '文字段落',
      color: '#666',
      font_weight: 500,
    },
  }, {
    tag_name: TagName.TEXT1,
    tag_props: {
      height: 20,
      width: 33.33,
      row_position: RowPosition.CENTER,
      column_position: ColumPosition.CENTER,
      font_size: 7,
      left: 66.66,
      top: 20,
      content: '文字段落',
      color: '#666',
      font_weight: 500,
    },
  }, {
    tag_name: TagName.TEXT1,
    tag_props: {
      height: 20,
      width: 33.33,
      row_position: RowPosition.CENTER,
      column_position: ColumPosition.CENTER,
      font_size: 7,
      left: 0,
      top: 20,
      content: '文字段落',
      color: '#666',
      font_weight: 500,
    },
  }],
};
