const DEFAULT_LOADER_URL = 'http://localhost:8000/index.html';
const PREFIX_NAME = {
  // 与渲染进程的交互
  RENDER_FROM_MAIN: 'RENDER_FROM_MAIN',
  RENDER_FROM_RENDER: 'RENDER_FROM_RENDER',

  // 与WebLoader相关的交互
  WEBLOADER_FROM_MAIN: 'WEBLOADER_FROM_MAIN',
  WEBLOADER_FROM_WEBLOADER: 'WEBLOADER_FROM_WEBLOADER',

  // 系统日志
  SYSTEM_WARN: 'SYSTEM_WARN',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
};


const COMMAND_FROM_RENDER = {
  RECORD: 'RECORD',
  TEST: 'TEST',
  PLAY: 'PLAY',
}

const COMMAND_FROM_WEBLOADER = {
  RECORD: 'RECORD',
}


module.exports = {
  DEFAULT_LOADER_URL,
  PREFIX_NAME,
  COMMAND_FROM_RENDER,
  COMMAND_FROM_WEBLOADER,
}
